### PR TITLE
Changed access specifier private -> protected to override the entire …

### PR DESCRIPTION
**Pull request by ubheamar**
Changed access specifier private -> protected to override the entire side panel HTML content.

### CODE REVIEW

**Comment by ubheamar** [comment]
Hello @vertonghenb , can you please review PR? let me know if required any changes

**Comment by vertonghenb** [comment]
@ubheamar what is the use case for this change? There might be a better way to accomplish what you need.

**Comment by ubheamar** [comment]
Actually, I want to use a side panel with tailwind CSS & also want to customize the entire side panel with a title, and subtitle & add some icons before the title.

I thought if I override the entire side panel.razor then it should be achievable via this package

**Comment by vertonghenb** [comment]
@ubheamar this PR won't help you achieve what you're looking for.

**Pull request closed without merging**
